version: "3.8"  # optional since v1.27.0
services:
#  frontend:
#    container_name: frontend
#    build: 
#      context: ./frontend
#    ports:
#      - 3000:3000
#    restart: always
#    volumes:
#       - ./frontend:/src/app/
#       - /src/app/node_modules
#       - /app/.next

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: user123


